### PR TITLE
Make FindEGL.cmake search for EGL/eglplatform.h only

### PR DESCRIPTION
**Pull request by aperezdc**
Only type definitions are used from the EGL headers, and the library is not ever linked in, so it seems more correct to check only for the header.

### CODE REVIEW

**Comment by zdobersek** [comment]
This is mergeable, but overall for the WPEBackend library we don't need to link against libEGL* at all. I can remove it in total later though.

**Comment by aperezdc** [comment]
@zdobersek: Now that you mention it, I could update the patch to remove the `find_library()` calls, but keep the check for the `EGL/eglplatform.h` header. As you say, the library is not actually used for linking after all.

**Comment by zdobersek** [comment]
Please go ahead and slim down the file, then.

**Comment by aperezdc** [comment]
Updated to search only for the `EGL/eglplatform.h` header.

@zdobersek PTAL.

**Pull request merged**
